# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
shared:
  image: node:18
jobs:
  validate-hashicorp-aws-base-sd-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/iiaas-base-sd-template.yaml
  publish-hashicorp-aws-base-sd-template:
    requires: validate-hashicorp-aws-base-sd-template
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/iiaas-base-sd-template.yaml

  validate-hashicorp-aws-ssl-sd-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/iiaas-ssl-sd-template.yaml
  publish-hashicorp-aws-ssl-sd-template:
    requires: [validate-hashicorp-aws-ssl-sd-template, publish-hashicorp-aws-base-sd-template]
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/iiaas-ssl-sd-template.yaml

  validate-sonatype-nexus-repository-sd-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/sonatype-nexus-repository-sd-template.yaml
  publish-sonatype-nexus-repository-sd-template:
    requires: [validate-sonatype-nexus-repository-sd-template, publish-hashicorp-aws-ssl-sd-template]
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/sonatype-nexus-repository-sd-template.yaml

  validate-react-app-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/react-app-sd-template.yaml
  publish-react-app-template:
    requires: validate-react-app-template
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/react-app-sd-template.yaml

  validate-kong-api-gateway-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/kong-api-gateway-sd-template.yaml
  publish-kong-api-gateway-template:
    requires: validate-kong-api-gateway-template
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/kong-api-gateway-sd-template.yaml

  validate-spring-webservice-basic-sd-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/spring-webservice-basic-sd-template.yaml
  publish-spring-webservice-basic-sd-template:
    requires: [validate-spring-webservice-basic-sd-template, publish-hashicorp-aws-base-sd-template]
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/spring-webservice-basic-sd-template.yaml

  validate-astraios-sd-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/astraios-sd-template.yaml
  publish-astraios-sd-template:
    requires: [validate-astraios-sd-template, publish-spring-webservice-basic-sd-template]
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/astraios-sd-template.yaml

  validate-elk-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/elk-sd-template.yaml
  publish-elk-template:
    requires: validate-elk-template
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/elk-sd-template.yaml

  validate-mlflow-docker-sd-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/mlflow-docker-sd-template.yaml
  publish-mlflow-docker-sd-template:
    requires: validate-mlflow-docker-sd-template
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/mlflow-docker-sd-template.yaml

  validate-docker-mailserver-sd-template:
    requires: [~pr, ~commit]
    steps:
      - install: npm install -g screwdriver-template-main
      - validate: template-validate
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/docker-mailserver-sd-template.yaml
  publish-docker-mailserver-sd-template:
    requires: validate-docker-mailserver-sd-template
    steps:
      - install: npm install -g screwdriver-template-main
      - publish: template-publish --tag latest
    environment:
      SD_TEMPLATE_PATH: adaptors/screwdriver-cd/templates/docker-mailserver-sd-template.yaml

  validate-install-docker:
    requires: [~pr, ~commit]
    steps:
      - validate: sd-cmd validate -f adaptors/screwdriver-cd/commands/install-docker/sd-command.yaml
  publish-install-docker:
    requires: [validate-install-docker]
    steps:
      - publish: sd-cmd publish -f adaptors/screwdriver-cd/commands/install-docker/sd-command.yaml -t latest

  validate-install-hashicorp-packer-ubuntu:
    requires: [~pr, ~commit]
    steps:
      - validate: sd-cmd validate -f adaptors/screwdriver-cd/commands/install-hashicorp-packer-ubuntu/sd-command.yaml
  publish-install-hashicorp-packer-ubuntu:
    requires: [validate-install-hashicorp-packer-ubuntu]
    steps:
      - publish: sd-cmd publish -f adaptors/screwdriver-cd/commands/install-hashicorp-packer-ubuntu/sd-command.yaml -t latest

  validate-install-hashicorp-terraform-ubuntu:
    requires: [~pr, ~commit]
    steps:
      - validate: sd-cmd validate -f adaptors/screwdriver-cd/commands/install-hashicorp-terraform-ubuntu/sd-command.yaml
  publish-install-hashicorp-terraform-ubuntu:
    requires: [validate-install-hashicorp-terraform-ubuntu]
    steps:
      - publish: sd-cmd publish -f adaptors/screwdriver-cd/commands/install-hashicorp-terraform-ubuntu/sd-command.yaml -t latest

  validate-install-jdk-17-ubuntu:
    requires: [~pr, ~commit]
    steps:
      - validate: sd-cmd validate -f adaptors/screwdriver-cd/commands/install-jdk-17-ubuntu/sd-command.yaml
  publish-install-jdk-17-ubuntu:
    requires: [validate-install-jdk-17-ubuntu]
    steps:
      - publish: sd-cmd publish -f adaptors/screwdriver-cd/commands/install-jdk-17-ubuntu/sd-command.yaml -t latest

  validate-install-maven-ubuntu:
    requires: [~pr, ~commit]
    steps:
      - validate: sd-cmd validate -f adaptors/screwdriver-cd/commands/install-maven-ubuntu/sd-command.yaml
  publish-install-maven-ubuntu:
    requires: [validate-install-maven-ubuntu]
    steps:
      - publish: sd-cmd publish -f adaptors/screwdriver-cd/commands/install-maven-ubuntu/sd-command.yaml -t latest

  validate-install-node:
    requires: [~pr, ~commit]
    steps:
      - validate: sd-cmd validate -f adaptors/screwdriver-cd/commands/install-node/sd-command.yaml
  publish-install-node:
    requires: [validate-install-node]
    steps:
      - publish: sd-cmd publish -f adaptors/screwdriver-cd/commands/install-node/sd-command.yaml -t latest

  validate-install-python-310:
    requires: [~pr, ~commit]
    steps:
      - validate: sd-cmd validate -f adaptors/screwdriver-cd/commands/install-python-310/sd-command.yaml
  publish-install-python-310:
    requires: [validate-install-python-310]
    steps:
      - publish: sd-cmd publish -f adaptors/screwdriver-cd/commands/install-python-310/sd-command.yaml -t latest
